//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pixel_Art_Tool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pixel_Art_Tool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primal Red	163	41	41
        ///Primal Orange	255	155	26
        ///Primal Yellow	255	222	2
        ///Primal Green	0	134	0
        ///Primal Blue	49	76	193
        ///Primal Purple	78	50	132
        ///Primal Gray	143	143	143
        ///Midnight Blue	0	23	59
        ///Dark Blue	10	61	136
        ///Business Blue	99	152	233
        ///Light Blue	208	232	255
        ///Blue Blue	25	111	255
        ///Laser Blue	17	224	255
        ///Moar Blue	0	57	255
        ///Boiled Denim	66	79	100
        ///Dark Brown	44	32	16
        ///Still Pretty Dark Brown	77	60	37
        ///Sepiagram	191	169	139
        ///Also Brown	54	44	25
        ///Hazel-Ish	108	100	77
        ///Dark Chocolate	35	30	23
        ///Cardboard Box	2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Trove_Neutral_by_Summer_Haas {
            get {
                return ResourceManager.GetString("Trove_Neutral_by_Summer_Haas", resourceCulture);
            }
        }
    }
}
